### ISSUE TITLE
CampaignBot records Caption as Reason Why if Caption is more than 1 message

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/gambit#725]
When members text in a multimessage response for Caption, campaign bot interprets the first message as response to Caption and the second as Ask Why. This leaves members confused because they didn't answer Ask Why but receive the Campaign Completed message. Members then text in Ask Why, receive the error message, text the support command, then ask us why they were unable to answer Ask Why / did the successfully complete the campaign. 

See MoCo user profile 208935562 for an example.

**Comment by aaronschachter** [comment]
This was a bug in the legacy `reportbacks` endpoint too -- It occurs because when the incoming text goes past a certain length, the Mobile Commons mData sends 2 POST requests -- splitting the incoming text at whatever the max length is for the first request.

#635 was an idea about checking for incoming messages instead of using mDatas at all to avoid this. Def a large T shirt size to try to figure this one out. Could be worth chatting with Mobile Commons to see if there's a possibility they can send us the entire text in one payload instead of splitting it into 2.

**Comment by deadlybutter** [comment]
for future thinking: twilio supports multiple messages as 1 request, it just specifies how many parts there are

**Comment by aaronschachter** [comment]
Assigning to @jamjensen for now per followup with Mobile Commons

**Comment by jamjensen** [comment]
Response from MoCo: 
![image](https://cloud.githubusercontent.com/assets/19572934/20223457/c2d421a0-a807-11e6-977f-55d09323f390.png)

**Comment by jamjensen** [comment]
Closing this until we have a better understanding of when MoCo will be able to prioritize this feature request. When deciding our next provider, the ability to send multiple messages within a single request should be taken into account.

**Comment by jamjensen** [comment]
On March 10th - after seeing this issue continue to disrupt user flows #800 - I followed up with Khaled. 

![image](https://cloud.githubusercontent.com/assets/19572934/23907682/4b887216-08a8-11e7-9809-92b76b339e41.png)

To which he responded: 
![image](https://cloud.githubusercontent.com/assets/19572934/23907705/5af18742-08a8-11e7-86e6-5860c9c21236.png)

Have yet to hear back from him.

**Comment by jamjensen** [comment]
❗️ Update from Khaled: "Move to Twilio will address the issue." 

![image](https://cloud.githubusercontent.com/assets/19572934/23921191/10f22292-08d4-11e7-9b08-3f6b542ba32e.png)

**Comment by aaronschachter** [comment]
@jamjensen Can we close #800 per the switch to Twilio?  I don't think it'd be worth trying to spend too much time on this internally.
