### ISSUE TITLE
Update Messaging Groups automatically when Campaign run id changes.

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/gambit#751]
Now, fields `mobilecommons_group_doing` and `mobilecommons_group_completed` are not updated when Campaign Run id changes.

**Comment by jamjensen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GAMBIT: Update Messaging Groups automatically when campaign run id changes](https://trello.com/c/qJzVpjdH/291-gambit-update-messaging-groups-automatically-when-campaign-run-id-changes)

**Comment by jamjensen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GAMBIT: Update Messaging Groups automatically when campaign run id changes](https://trello.com/c/qJzVpjdH/291-gambit-update-messaging-groups-automatically-when-campaign-run-id-changes)

**Comment by aaronschachter** [comment]
As mentioned -- https://github.com/DoSomething/gambit/issues/775#issuecomment-291535058 I'm leaning toward Gambit requesting the Group ID's from the DS Messaging Groups API (MGAPI) instead of maintaining its own cache (or storing the ID's in a cache on Contentful). [The MGAPI maintains its own cache in Mongo to avoid querying out to Mobile Commons for every request.](https://github.com/DoSomething/messaging-groups-api/blob/30bb21d4c1b1230a0b348c64c45938d8eb6ec638/lib/routes/api.js#L32)

If we have that in place, the only issue left is posting to the MGAPI when we have a new campaign and/or campaign run -- currently in place when the app starts up based on the values set in `CAMPAIGNBOT_CAMPAIGNS`. I'd like to deprecate `CAMPAIGNBOT_CAMPAIGNS` entirely to avoid an app restart to add/remove a Campaign, it also adds overhead when we're maintaining what's available via Contentful through published keywords. Some ideas:

* In the Gambit **GET** `/campaigns` route -- when querying out to MGAPI and a Messaging Group is not found, make the POST call there to create it and return the new group ID

* Add a [Slothbot](https://github.com/dosomething/slothbot) command to POST to MGAPI to create the Groups -- there's already a manual step of a Gambit admin informing @sergii-tkachenko / Quicksilver team that the group id's need to change

The first option seems a bit more error proof.
