### ISSUE TITLE
Investigate why campaign status wasn't updated

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/gambit#764]
<img width="1042" alt="screen shot 2016-12-01 at 1 09 10 pm" src="https://cloud.githubusercontent.com/assets/897368/20806062/604caf50-b7c7-11e6-87e8-d3bbc7ddb40a.png">

**Comment by aaronschachter** [comment]
This is likely an order of operations issue. If we're closing a Campaign and we remove the Campaign ID from `CAMPAIGNBOT_CAMPAIGNS` while its status is Active -- that Campaign status will never be updated to closed on [app start](https://github.com/DoSomething/gambit/blob/fbe1ead5067a50f137f1573cb5954e8efb212a0f/server.js#L138).

One idea to resolve is to change `loadCampaigns` to just update the cache for all Campaigns we have documents for.

@deadlybutter Can you update issue description with actual text? The screenshots of Slack rooms won't help surface this issue when searching.

**Comment by aaronschachter** [comment]
I've pondering using `campaigns.findById` every time we need to load a Campaign instead of keeping them in memory on app start -- deprecating the `CAMPAIGNBOT_CAMPAIGNS` config variable altogether in favor of a new `campaignbot` boolean property on the Campaign model that admins can use to enable/disable CampaignBot campaigns. This would avoid needing to restart the app to turn campaigns on/off... although it would slow things down. We load keywords all in memory too -- which would be another Mongo query to execute if a `keyword` parameter is passed in an incoming chatbot request.

**Comment by deadlybutter** [comment]
+1 to loading from DB instead of memory where possible

**Comment by aaronschachter** [comment]
Closing this, as the investigation is done. This will be fixed when #775 is resolved.
