### ISSUE TITLE
Relative Reminder messages

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#79]
Refs https://github.com/DoSomething/gambit-conversations/issues/74

As a developer, I want Conversations API to support using Customer.io to send a Campaign Completion Reminder message to a User for a Gambit Campaign, to be delivered X hours after the Signup Created Date if the User hasn't completed the Campaign.

cc @rapala61 @sergii-tkachenko

**Comment by aaronschachter** [comment]
It may be easier to repurpose Quicksilver Dispatch Delayed Messages for this -- to be determined post launch.

**Comment by sergii-tkachenko** [comment]
One significant change since our decision to repurpose Quicksilver Dispatch Delayed Messages: Quicksilver can't see Phoenix Next signups anymore. The reason for that is breaking change in Rogue, it does not submit signup copies to Phoenix Ashes anymore.

This change defies the logic for selecting relative reminders, as it just won't have access to all signups and reportbacks. Thus, Quicksilver Dispatch Delayed Messages will be retired.
