### ISSUE TITLE
GET /campaigns/:id error: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#990]
_BUG_
-------------------
#### Current Behavior
- Seeing a bunch of 500 errors on staging to `GET /campaigns/2003` with a `Cannot read property 'fields' of undefined` error. It's not happening on production.  My hunch is that this is from https://github.com/DoSomething/gambit-conversations/issues/189. [Campaign 2003 is a valid Phoenix Campaign](https://thor.dosomething.org/api/v1/campaigns/2003), but it doesn't have any Keywords defined in Contentful.

#### Desired Behavior
- Either send a 200 back with empty `templates` and `keywords`, or send a 404 error. I'm leaning toward a 200 with empty properties -- curious for your input @rapala61 and @sergii-tkachenko. 

Technically a Campaign could still have templates without a Contentful Campaign defined, we'd just render the default Campaign template values. The lack of keywords would indicate it's not currently available on Gambit -- but begs the question, should it be a 404 if not currently available on Gambit? I think the answer is yes - on the Gambit admin side, we'd want to see the templates and messages for Campaigns no longer available for members to complete.

#### Why This Matters
- 500 seems like the wrong error code to return here, if we should return an error at all.

**Comment by rapala61** [comment]
This issue is not the cause of Convo#189, but it plays a part in the overall issue. I've been toying with it for a bit, its kinda confusing because is a combination of at least 2 bugs (in both, Convo and Campaigns) acting in unison.

Bug #1 - Campaigns: Campaigns like `2003` ends in a 500 error. If `2003` is not a gambit campaign, I think we should stop it from being included in any response by default as it's just an error waiting to happen up the chain. We could include them in very specific cases if we are asked (via a query param?) and whoever asks for them need to handle it as a keyword-less campaign.

Bug #2 (Convo#189) - Convo: There is a [bug](https://github.com/DoSomething/gambit-conversations/blob/master/lib/gambit-campaigns.js#L26) when catching errors in the `executeGet` (and other methods) of the `gambit-campaigns` lib that returns the error response as a false positive response. This makes the parent promise believe it is receiving a valid campaign when its actually receiving an error object. My hunch is that Convo#189 is directly related to this bug.

Pending what decision is made on Bug #1, I have these cases to think about when it comes to a campaign:

a) A campaign exists but it's not valid because it doesn't have Keywords. 
b) A campaign exists but it's not valid because it has a status of closed.
c) A campaign exists and it's valid because has keywords and has a status of active.
d) A campaign doesn't exist.

Getting rid of `a)` as a case could clear up the ambiguity when we talk about "invalid gambit campaigns". We would end up with a 200 response for `b)` and `c)`, and a 404 response for `a)` and `d)`.

**Comment by aaronschachter** [comment]
Re Bug#1: I do think a `GET /campaigns/:id` request is useful for a Campaign not available on Gambit from the admin / editorial side, so we're able to view the template content for a Campaign without requiring keywords (meaning it's published, and available on Contentful thus available on Gambit). 

Historically we went with once the keyword exists, it's "published" in Gambit world - vs creating any kind of status (another fields for an admin to maintain / developer to check).

**Comment by rapala61** [comment]
Exactly, I agree. We still want to be able to return the "Invalid campaigns" that fit the category `a) A campaign exists but it's not valid because it doesn't have Keywords.`. I just think that we should not return them by default, because it's not used anywhere but for editorial/admin purposes. This way we simplify the concept of what is an invalid campaign in Gambit: `b) A campaign exists but it's not valid because it has keywords but a status of closed.`.

**Comment by aaronschachter** [comment]
Sounds like we're on the same page! Our `GET /campaigns/:id` should return a 200 with:
*  the Phoenix campaign details it currently returns
*  an empty `keywords` property
*  it'd make sense to still render the templates for the Campaign with the default Contentul templates if the override Campaign hasn't been added in Contentful.. but i think for launch it's fine to get away with an empty `templates` if we don't have time for it. 

I have been itching to refactor the Contentful Campaign entry requests to make a single request for both the default Campaign and override Campaign entries instead of 2 requests.. but again, it's a nice-to-have cleanup task.

**Comment by rapala61** [comment]
🤔 . I guess the problem is that we haven't stated clearly, what the responsibility of this endpoint is. 

If it's **only** responsibility is to fetch a campaign if it exists in Phoenix, then I agree with your statement above. Basically we don't care if its a Valid Gambit campaign or not (has/doesn't have keywords, is closed/is open), these concepts are implementation dependent at the client level.

If we do care about the validity of the campaign, other than it existing in Phoenix, then I don't agree with just returning 200 minus the keywords.

**Comment by aaronschachter** [comment]
>  these concepts would be implementation dependent at the client level

Gambini  + the Campaigns endpoint exist because we were just building the foundations of the Phoenix Contentful space, so we didn't want to add 20 new template fields to a Campaign there --  and didn't want to slow down Gambit development by adding 20 new fields to Phoenix Ashes.

I think referring to the Campaign as valid or invalid is where gets unclear. There's a use for publishing a keyword for a closed Campaign - the User gets the message back that this Campaign isn't in business at the moment, but text MENU to find one that does (in Gambit's case -- a Campaign with `active` Phoenix status that also has at least one keyword defined via Gambini)

**Comment by rapala61** [comment]
Now I feel we are in the same page 😁. Thanks for the context.

I tagged as TGM blocker/blocker. Are you taking on this next or should I recalibrate and tackle this first?
